language: node_js
notifications:
email: false
node_js:
  - "4"
  - "5"
script:
  - npm test
after_success:
  - npm install coveralls
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage